# Generated by Django 5.2 on 2025-05-03 00:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_category_options_alter_losslog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
