# Generated by Django 5.2 on 2025-05-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_discountcode_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Analytics 📈',
                'verbose_name_plural': 'Analytics 📈',
                'managed': False,
            },
        ),
    ]
